name: stream_opus
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffi: ^2.1.3
flutter:

  plugin:
    platforms:
      android:
        package: com.opus.me.stream_opus
        pluginClass: StreamOpusPlugin
      ios:
        pluginClass: StreamOpusPlugin

